version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
     - "5000:5000"
  tests:
    build:
        context: .
        dockerfile: Dockerfile.dev
        command: ["npm", "run", "test"]
    
        
    
      